import { Document, Packer, Paragraph, TextRun, AlignmentType } from 'docx';
import { jsPDF } from 'jspdf';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], form=$('#case-form');
const DRAFT='pa-sekayu-draft-v2', ARCHIVE='pa-sekayu-archive-v2', today=new Date().toISOString().slice(0,10); $('input[name="entryDate"]').value=today;
const date=v=>{const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?null:d}, age=v=>{const b=date(v),n=new Date();if(!b||b>n)return null;let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||n.getMonth()===b.getMonth()&&n.getDate()<b.getDate())a--;return a>=0?a:null}, fmt=v=>date(v)?.toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})||'', esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nik(v){v=v.replace(/\D/g,'');if(v.length!==16)return{error:'NIK harus terdiri dari 16 digit.'};const d=+v.slice(6,8),m=+v.slice(8,10),y=+v.slice(10,12),female=d>40,day=female?d-40:d,yy=y<=+String(new Date().getFullYear()).slice(2)?2000+y:1900+y,val=`${yy}-${String(m).padStart(2,'0')}-${String(day).padStart(2,'0')}`,x=date(val);return !x||x.getFullYear()!==yy||x.getMonth()+1!==m||x.getDate()!==day||x>new Date()?{error:'Tanggal lahir pada NIK tidak valid.'}:{date:val,gender:female?'Perempuan':'Laki-laki'}}
function wire(p){const n=$(`[name="${p}Nik"]`),b=$(`[name="${p}BirthDate"]`),a=$(`[name="${p}Age"]`),g=$(`[name="${p}Gender"]`),h=$(`#${p}-hint`),calc=()=>a.value=b.value&&age(b.value)!==null?`${age(b.value)} tahun`:'';n.oninput=()=>{n.value=n.value.replace(/\D/g,'').slice(0,16);if(!n.value){h.textContent='Opsional bila tidak tersedia.';return}const r=nik(n.value);if(r.error){h.textContent=r.error;h.className='error';return}b.value=r.date;g.value=r.gender;calc();h.textContent=`Terbaca: ${fmt(r.date)} · ${r.gender}`;h.className=''};b.oninput=calc;calc()} wire('a');wire('b');
$('input[name="marriageDate"]').oninput=e=>$('input[name="marriageDuration"]').value=age(e.target.value)!==null?`${age(e.target.value)} tahun`:'';
function children(data=[]){const box=$('#children');box.innerHTML='';if(!data.length){box.innerHTML='<p class="muted">Belum ada data anak.</p>';return}data.forEach(addChild)}
function addChild(x={}){const box=$('#children');$('.muted',box)?.remove();const r=document.createElement('div');r.className='child';r.innerHTML=`<label>Nama anak<input name="childName" value="${esc(x.name)}"></label><label>Tempat lahir<input name="childPlace" value="${esc(x.place)}"></label><label>Tanggal lahir<input name="childBirth" type="date" value="${esc(x.birth)}"><small class="child-age">${age(x.birth)!=null?age(x.birth)+' tahun':'Umur otomatis'}</small></label><button type="button">×</button>`;$('input[name="childBirth"]',r).oninput=e=>$('.child-age',r).textContent=age(e.target.value)!=null?`${age(e.target.value)} tahun`:'Umur otomatis';$('button',r).onclick=()=>{r.remove();if(!$('.child',box))children()};box.append(r)}$('#add-child').onclick=()=>addChild();
function data(){const d=Object.fromEntries(new FormData(form));d.caseType=$('input[name="caseType"]:checked').value;d.children=$$('.child').map(r=>({name:$('[name="childName"]',r).value,place:$('[name="childPlace"]',r).value,birth:$('[name="childBirth"]',r).value}));return d}
function alertMsg(t,e=false){const a=$('#alert');a.textContent=t;a.className=e?'alert error':'alert';clearTimeout(window.at);window.at=setTimeout(()=>a.classList.add('hidden'),4000)}
function valid(){const bad=$$('[required]',form).filter(x=>!x.value.trim());if(bad.length){bad[0].focus();alertMsg(`${bad.length} kolom wajib belum diisi.`,true);return false}if(nik($('[name="aNik"]').value).error){alertMsg('Periksa NIK pihak pertama.',true);return false}return true}
function saveDraft(){localStorage.setItem(DRAFT,JSON.stringify(data()));alertMsg('Konsep tersimpan lokal.')}function archive(){if(!valid())return;const d=data();d.id=d.id||`case-${Date.now()}`;let a=JSON.parse(localStorage.getItem(ARCHIVE)||'[]');const i=a.findIndex(x=>x.id===d.id);i<0?a.unshift(d):a[i]=d;localStorage.setItem(ARCHIVE,JSON.stringify(a));renderArchive();alertMsg('Perkara disimpan ke arsip lokal.')}
function renderArchive(){const a=JSON.parse(localStorage.getItem(ARCHIVE)||'[]'),box=$('#archive');box.innerHTML=a.length?a.map(x=>`<li class="archive-item"><span><b>${esc(x.caseNumber||'Tanpa nomor')}</b><small>${esc(x.aName||'-')} / ${esc(x.bName||'-')}</small></span><span><button data-open="${x.id}">Buka</button><button data-del="${x.id}">Hapus</button></span></li>`).join(''):'<li class="muted">Belum ada arsip.</li>';$$('[data-open]').forEach(b=>b.onclick=()=>load(JSON.parse(localStorage.getItem(ARCHIVE)||'[]').find(x=>x.id===b.dataset.open)));$$('[data-del]').forEach(b=>b.onclick=()=>{localStorage.setItem(ARCHIVE,JSON.stringify(JSON.parse(localStorage.getItem(ARCHIVE)||'[]').filter(x=>x.id!==b.dataset.del)));renderArchive()})}
function load(d){if(!d)return;Object.entries(d).forEach(([k,v])=>{if(k!=='children'&&k!=='caseType'&&form.elements[k])form.elements[k].value=v});$(`input[name="caseType"][value="${d.caseType}"]`).checked=true;children(d.children||[]);['a','b'].forEach(p=>{const n=$(`[name="${p}Nik"]`);if(n.value)n.dispatchEvent(new Event('input'))});if(d.marriageDate)$('[name="marriageDate"]').dispatchEvent(new Event('input'));preview()}
function preview(){const d=data(),a=d.caseType==='cerai-talak'?'Pemohon':'Penggugat',b=d.caseType==='cerai-talak'?'Termohon':'Tergugat';$('#preview').className='preview';$('#preview').innerHTML=`<h4>Pratinjau ringkas</h4><p><b>${a}:</b> ${esc(d.aName||'-')} (${esc(d.aAge||'-')})<br><b>${b}:</b> ${esc(d.bName||'-')} (${esc(d.bAge||'-')})<br><b>Perkawinan:</b> ${esc(d.marriageDate?fmt(d.marriageDate):'-')}<br><b>Alasan:</b> ${esc((d.facts||'-').slice(0,400))}</p>`}
function legal(){const d=data(),talak=d.caseType==='cerai-talak';return{...d,a:talak?'Pemohon':'Penggugat',b:talak?'Termohon':'Tergugat',facts:d.facts||'-',claims:d.claims||'-',entry:fmt(d.entryDate||today)}}
const para=(t,o={})=>new Paragraph({alignment:o.align||AlignmentType.LEFT,spacing:{before:o.before??100,after:o.after??100},children:[new TextRun({text:t,size:o.size||22,bold:o.bold||false})]});
async function word(){if(!valid())return;const d=legal(),lines=[para('GUGATAN CERAI',{align:AlignmentType.CENTER,bold:true,size:30,after:250}),para(`Nomor Perkara: ${d.caseNumber||'-'}`,{bold:true}),para('Kepada Yth.'),para('Ketua Pengadilan Agama Sekayu'),para('di Sekayu',{after:220}),para(`Perihal: ${d.caseType==='cerai-talak'?'Permohonan Cerai Talak':'Gugatan Cerai'}`,{bold:true}),para(`Yang bertanda tangan di bawah ini, ${d.a}:`),para(`Nama lengkap: ${d.aName}`),para(`NIK: ${d.aNik||'-'}`),para(`Tempat, tanggal lahir: ${d.aBirthPlace||'-'}, ${fmt(d.aBirthDate)}`),para(`Umur: ${d.aAge||'-'}`),para(`Alamat: ${d.aAddress}`),para(`Selanjutnya disebut ${d.a}.`),para(`${d.b} bernama ${d.bName}, beralamat di ${d.bAddress}.`),para(`Selanjutnya disebut ${d.b}.`),para('Adapun alasan-alasan perkara adalah sebagai berikut:',{bold:true}),para(d.facts),para('Berdasarkan uraian tersebut, dimohon putusan sebagai berikut:',{bold:true}),para(d.claims),para('Demikian dokumen ini dibuat untuk dipergunakan sebagaimana mestinya.'),para(`Sekayu, ${d.entry}`,{align:AlignmentType.RIGHT}),para(d.a,{align:AlignmentType.RIGHT}),para('',{after:400}),para(d.aName,{align:AlignmentType.RIGHT,bold:true})];const blob=await Packer.toBlob(new Document({sections:[{properties:{page:{margin:{top:1080,right:1080,bottom:1080,left:1080}}},children:lines}]}));download(blob,`gugatan-${d.caseType}-${Date.now()}.docx`);alertMsg('Dokumen Word berhasil diunduh.')}
function pdf(){if(!valid())return;const d=legal(),p=new jsPDF({unit:'pt',format:'a4'}),m=54,w=p.internal.pageSize.getWidth(),h=p.internal.pageSize.getHeight();let y=55;p.setFont('helvetica','normal');const add=(s,o={})=>{p.setFontSize(o.size||11);p.setFont('helvetica',o.bold?'bold':'normal');const ls=p.splitTextToSize(s,w-m*2);ls.forEach(l=>{if(y>h-55){p.addPage();y=55}p.text(l,o.align==='right'?w-m:m,y,{align:o.align||'left'});y+=o.leading||17});y+=3};add('GUGATAN CERAI',{size:16,bold:true});add(`Nomor Perkara: ${d.caseNumber||'-'}`,{bold:true});['Kepada Yth.','Ketua Pengadilan Agama Sekayu','di Sekayu'].forEach(x=>add(x));add(`Perihal: ${d.caseType==='cerai-talak'?'Permohonan Cerai Talak':'Gugatan Cerai'}`,{bold:true});[`${d.a}: ${d.aName}`,`NIK: ${d.aNik||'-'}`,`Lahir: ${d.aBirthPlace||'-'}, ${fmt(d.aBirthDate)}`,`Umur: ${d.aAge||'-'}`,`Alamat: ${d.aAddress}`,`${d.b}: ${d.bName}`,`Alamat: ${d.bAddress}`,'Alasan perkara:',d.facts,'Petitum:',d.claims].forEach(x=>add(x));add(`Sekayu, ${d.entry}`,{align:'right'});add(d.a,{align:'right'});add(d.aName,{align:'right',bold:true});p.save(`gugatan-${d.caseType}-${Date.now()}.pdf`);alertMsg('Dokumen PDF berhasil diunduh.')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$$('input[name="caseType"]').forEach(x=>x.onchange=()=>{$('#a-title').textContent=x.checked&&x.value==='cerai-talak'?'Data Pemohon':'Data Penggugat';$('#b-title').textContent=x.checked&&x.value==='cerai-talak'?'Data Termohon':'Data Tergugat';preview()});$$('textarea').forEach(x=>x.oninput=()=>{$(`#${x.name}-count`).textContent=`${x.value.length} karakter`;preview()});form.oninput=()=>{clearTimeout(window.st);window.st=setTimeout(saveDraft,700);preview()};$('#save-draft').onclick=saveDraft;$('#save-archive').onclick=archive;$('#export-word').onclick=word;$('#export-pdf').onclick=pdf;$('#reset').onclick=()=>{if(confirm('Bersihkan formulir dan konsep?')){localStorage.removeItem(DRAFT);form.reset();children();$('input[name="entryDate"]').value=today;preview()}};$('#export-json').onclick=()=>download(new Blob([JSON.stringify({cases:JSON.parse(localStorage.getItem(ARCHIVE)||'[]'),draft:JSON.parse(localStorage.getItem(DRAFT)||'null')},null,2)],{type:'application/json'}),`arsip-pa-sekayu-${today}.json`);$('#import-json').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);localStorage.setItem(ARCHIVE,JSON.stringify(x.cases||x));renderArchive();if((x.cases||x)[0])load((x.cases||x)[0]);alertMsg('Data berhasil diimpor.')}catch{alertMsg('File JSON tidak valid.',true)}};r.readAsText(e.target.files[0])};children();renderArchive();const old=localStorage.getItem(DRAFT);if(old)load(JSON.parse(old));preview();
